### ISSUE TITLE
Edit paper page should save changes to the author list

### ISSUE THREAD

**Issue by swt2public** [MasterCarl/rails-exercise-16#39]
Given a paper with one author
And another author called 'Peter Plagiarist'
When a user visits the paper's edit page
And the selects 'Peter Plagiarist' as first author
And submits the form
Then 'Peter Plagiarist' should be author of the paper

Expected #<activerecord::associations::collectionproxy [#<author id: 1, first_name: "alan", last_name: "turing", homepage: "http://wikipedia.de/alan_turing", created_at: "2016-11-13 22:01:02", updated_at: "2016-11-13 22:01:02">]> to include #<author id: 2, first_name: "peter", last_name: "plagiarist", homepage: "http://wikipedia.de/alan_turing", created_at: "2016-11-13 22:01:02", updated_at: "2016-11-13 22:01:02">
diff:
@@ -1,7 +1,7 @@
-[#<author:0x00000006ed95a8
-  id: 2,
-  first_name: "peter",
-  last_name: "plagiarist",
+[#<author:0x00000006d3da00
+  id: 1,
+  first_name: "alan",
+  last_name: "turing",
   homepage: "http://wikipedia.de/alan_turing",
   created_at: sun, 13 nov 2016 22:01:02 utc +00:00,
   updated_at: sun, 13 nov 2016 22:01:02 utc +00:00>]

**Comment by swt2public** [comment]
Given a paper with one author
And another author called 'Peter Plagiarist'
When a user visits the paper's edit page
And the selects 'Peter Plagiarist' as first author
And submits the form
Then 'Alan Turing' should not be author of the paper

Expected #<activerecord::associations::collectionproxy [#<author id: 1, first_name: "alan", last_name: "turing", homepage: "http://wikipedia.de/alan_turing", created_at: "2016-11-13 22:27:36", updated_at: "2016-11-13 22:27:36">, #<author id: 2, first_name: "peter", last_name: "plagiarist", homepage: "http://wikipedia.de/alan_turing", created_at: "2016-11-13 22:27:36", updated_at: "2016-11-13 22:27:36">]> not to include #<author id: 1, first_name: "alan", last_name: "turing", homepage: "http://wikipedia.de/alan_turing", created_at: "2016-11-13 22:27:36", updated_at: "2016-11-13 22:27:36">
diff:

@@ -1,7 +1,14 @@
-[#<author:0x0000000873a868
+[#<author:0x00000008531bc0
   id: 1,
   first_name: "alan",
   last_name: "turing",
-  homepage: "http://wikipedia.de/alan_turing",
-  created_at: sun, 13 nov 2016 22:27:36 utc +00:00,
-  updated_at: sun, 13 nov 2016 22:27:36 utc +00:00>,
- #<author:0x000000085319e0
-  id: 2,
-  first_name: "peter",
-  last_name: "plagiarist",
  homepage: "http://wikipedia.de/alan_turing",
  created_at: sun, 13 nov 2016 22:27:36 utc +00:00,
  updated_at: sun, 13 nov 2016 22:27:36 utc +00:00>]

**Comment by MasterCarl** [comment]
SIgh...
